[versions]
espressoCore = "3.7.0"
gradle = "8.13.1"
gradleVersionsPlugin = "0.53.0"
junit = "1.3.0"
kotlinGradlePlugin = "2.2.21"
androixtest = "1.7.0"
uiautomator = "2.3.0"

[libraries]
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
rules = { module = "androidx.test:rules", version.ref = "androixtest" }
runner = { module = "androidx.test:runner", version.ref = "androixtest" }
uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }

[plugins]
gradle-versions-plugin = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
